In [6]:
# Fake News Classifier Using LSTM

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('/content/sample_data/train.csv')

In [9]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [10]:
# Drop Nan values

df = df.dropna()

In [11]:
# Getting the Independent features

X = df.drop('label', axis = 1)

In [12]:
# Get the Dependent features

y = df['label']

In [13]:
X.shape, y.shape

((18285, 4), (18285,))

In [14]:
#

import tensorflow as tf

In [15]:
tf.__version__

'2.4.1'

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [17]:
# voabulary size

voc_size = 5000

In [18]:
## One hot Representation

messages = X.copy()

In [19]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [21]:
messages.reset_index(inplace = True)

In [22]:
import nltk
import re
from nltk.corpus import stopwords

In [23]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [24]:
# Dataset Preprocessing

from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
  print(i)
  review = re.sub('[^a-zA-Z]',' ', messages['title'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [25]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [26]:
onehot_repr = [one_hot(words, voc_size) for words in corpus]
onehot_repr

[[15, 4486, 446, 2327, 1408, 2532, 1232, 4475, 352, 3019],
 [296, 75, 2433, 702, 2865, 4252, 301],
 [3803, 913, 2118, 761],
 [3808, 4356, 3751, 4244, 3013, 2841],
 [3844, 2865, 2594, 4103, 1153, 5, 2865, 2322, 2719, 4338],
 [1611,
  4797,
  534,
  4506,
  2754,
  423,
  3369,
  4105,
  986,
  4986,
  1753,
  2271,
  2650,
  1634,
  301],
 [3690, 3670, 849, 4753, 2647, 4812, 1686, 3006, 270, 90, 257],
 [3240, 511, 2686, 3246, 1649, 459, 423, 346, 270, 90, 257],
 [2776, 1226, 76, 1161, 926, 1663, 3446, 481, 423, 3905],
 [1766, 3615, 4206, 4192, 1723, 4183, 3015, 1334],
 [4121, 3698, 60, 897, 4925, 4546, 3108, 3542, 210, 434, 3500],
 [4244, 2300, 1408, 1663, 423, 1649],
 [4224, 4975, 497, 1702, 4042, 1689, 364, 3676, 3672],
 [3629, 1387, 2931, 535, 624, 2291, 3802, 270, 90, 257],
 [299, 604, 1208, 575, 159, 270, 90, 257],
 [1848, 2227, 3350, 1542, 2925, 4305, 1544, 4600, 1935, 1471],
 [2362, 1648, 75],
 [3348, 3007, 2711, 4685, 423, 4040, 2441, 301],
 [32, 1580, 2433, 2232, 4512, 492, 148

In [27]:
## Embedding Representation

sent_length = 20
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 ... 4475  352 3019]
 [   0    0    0 ... 2865 4252  301]
 [   0    0    0 ...  913 2118  761]
 ...
 [   0    0    0 ...  270   90  257]
 [   0    0    0 ... 1523 2823 3830]
 [   0    0    0 ... 1008 1652 1383]]


In [28]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   15,
       4486,  446, 2327, 1408, 2532, 1232, 4475,  352, 3019], dtype=int32)

In [29]:
# Creating a model

embedding_vector_features = 40

model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [31]:
len(embedded_docs), y.shape

(18285, (18285,))

In [33]:
embedded_docs

array([[   0,    0,    0, ..., 4475,  352, 3019],
       [   0,    0,    0, ..., 2865, 4252,  301],
       [   0,    0,    0, ...,  913, 2118,  761],
       ...,
       [   0,    0,    0, ...,  270,   90,  257],
       [   0,    0,    0, ..., 1523, 2823, 3830],
       [   0,    0,    0, ..., 1008, 1652, 1383]], dtype=int32)

In [34]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [35]:
import numpy as np

X_final = np.array(embedded_docs)
y_final = np.array(y)

In [36]:
X_final

array([[   0,    0,    0, ..., 4475,  352, 3019],
       [   0,    0,    0, ..., 2865, 4252,  301],
       [   0,    0,    0, ...,  913, 2118,  761],
       ...,
       [   0,    0,    0, ...,  270,   90,  257],
       [   0,    0,    0, ..., 1523, 2823, 3830],
       [   0,    0,    0, ..., 1008, 1652, 1383]], dtype=int32)

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size = 0.33, random_state = 42)

In [38]:
## Model Training


In [49]:
model.fit(X_train, y_train, validation_data = (X_test, y_test), epochs = 10, batch_size = 64)

Epoch 1/10
192/192 [==============================] - 4s 11ms/step - loss: 0.4965 - accuracy: 0.7232 - val_loss: 0.2106 - val_accuracy: 0.9138
Epoch 2/10
192/192 [==============================] - 2s 9ms/step - loss: 0.1543 - accuracy: 0.9425 - val_loss: 0.1942 - val_accuracy: 0.9233
Epoch 3/10
192/192 [==============================] - 2s 9ms/step - loss: 0.1047 - accuracy: 0.9603 - val_loss: 0.2170 - val_accuracy: 0.9110
Epoch 4/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0729 - accuracy: 0.9724 - val_loss: 0.2255 - val_accuracy: 0.9138
Epoch 5/10
192/192 [==============================] - 2s 9ms/step - loss: 0.0569 - accuracy: 0.9809 - val_loss: 0.2383 - val_accuracy: 0.9132
Epoch 6/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0431 - accuracy: 0.9858 - val_loss: 0.2953 - val_accuracy: 0.9118
Epoch 7/10
192/192 [==============================] - 2s 9ms/step - loss: 0.0307 - accuracy: 0.9911 - val_loss: 0.3503 - val_accuracy: 0.9147
Epoch

In [52]:
## Adding Dropout

from tensorflow.keras.layers import Dropout

# Creating model

model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics= ['accuracy'])

In [58]:
model.fit(X_train, y_train, validation_data = (X_test, y_test), epochs = 20, batch_size = 64)

Epoch 1/20
192/192 [==============================] - 2s 9ms/step - loss: 0.0143 - accuracy: 0.9953 - val_loss: 0.4382 - val_accuracy: 0.9167
Epoch 2/20
192/192 [==============================] - 2s 9ms/step - loss: 0.0153 - accuracy: 0.9948 - val_loss: 0.5086 - val_accuracy: 0.9112
Epoch 3/20
192/192 [==============================] - 2s 9ms/step - loss: 0.0195 - accuracy: 0.9931 - val_loss: 0.4958 - val_accuracy: 0.9148
Epoch 4/20
192/192 [==============================] - 2s 9ms/step - loss: 0.0103 - accuracy: 0.9967 - val_loss: 0.5066 - val_accuracy: 0.9117
Epoch 5/20
192/192 [==============================] - 2s 9ms/step - loss: 0.0091 - accuracy: 0.9967 - val_loss: 0.5169 - val_accuracy: 0.9147
Epoch 6/20
192/192 [==============================] - 2s 8ms/step - loss: 0.0067 - accuracy: 0.9981 - val_loss: 0.6272 - val_accuracy: 0.9132
Epoch 7/20
192/192 [==============================] - 2s 9ms/step - loss: 0.0058 - accuracy: 0.9981 - val_loss: 0.5523 - val_accuracy: 0.9130
Epoch 

In [59]:
# Performance Metics and Accuracy

y_pred = model.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [60]:
from sklearn.metrics import confusion_matrix

In [61]:
confusion_matrix(y_test, y_pred)

array([[3151,  268],
       [ 281, 2335]])

In [62]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9090306545153273